### ISSUE TITLE
Release new version for Thunderbird 78

### ISSUE THREAD

**Issue by Juraj-Masiar** [speedball2001/nompsort-mx#1]
Hello,
The final Thunderbird 78 has been released (two days ago) and existing users are now being upgraded:
https://www.ghacks.net/2020/09/15/automatic-thunderbird-upgrade-to-version-78-x-has-started/

Could you release updated version to the Thunderbird addons store?
https://addons.thunderbird.net/thunderbird/addon/no-message-pane-sort-by-mouse/

Thank you! :)

**Comment by speedball2001** [comment]
@Juraj-Masiar Did you install the release from https://github.com/speedball2001/nompsort-mx/releases/tag/2.0beta1 already?

**Comment by Juraj-Masiar** [comment]
Thank you @speedball2001 for the link! I haven't yet, I was hoping it will be released to the store when new Thunderbird gets released.
So why not release it to the store?

**Comment by speedball2001** [comment]
I will submit it to addons.thunderbird.net sometime in the future. But in the meantime you can you the beta. Let me know if it works for you.

**Comment by Juraj-Masiar** [comment]
I'm mean, sure it works for me, but what about the rest of the  2,520 users you have there? They are being auto-upgraded to 78 right now and your addon will not work for them. If the new version is ready, why not release it? All you need to do is upload the zip there. It should only take a minute, right?

**Comment by speedball2001** [comment]
As I said: I'll upload it to addons.thunderbird.net. Noone outside the Thunderbird devteam knew when they'd enable the auto-update to TB78. In the meantime I had to keep the addon working for everyone with TB68.  As you probably know addons for TB68 and TB78 are incompatible due to internal changes in Thunderbird.

**Comment by Juraj-Masiar** [comment]
I'm actually addon developer as well :) so I'm aware of what's happening regarding compatibility. That's why I'm here.

Don't worry about users of 68, if you set `"strict_min_version": "78.0"` in your manifest file (which you already did), then only users that have Thunderbird 78 will be updated and existing users with Thunderbird 68 or 77 and below will stay on the old version.

BTW, Thunderbird releases follows Firefox ESR releases so the new version 78 was suppose to be released on next Tuesday, so they did started rollout a week early.
https://wiki.mozilla.org/Release_Management/Calendar
