### ISSUE TITLE
Add-On is limited to 102.0 - 102.0.1 is about to be released soon.

### ISSUE THREAD

**Issue by jobisoft** [speedball2001/nompsort-mx#10]
Hi,

it seems this add-on works in Thunderbird 102, but it is limited to 102.0 and not 102.*. That means, it will be deactivated when 102.0.1 is released next week. Could you have a look? Thanks!

**Comment by speedball2001** [comment]
Hi @jobisoft 

since the addon directly goes to the message pane DOM, what would be a sensible value for max_version/strict_max_version?
