### ISSUE TITLE
Not compatible with TB 115

### ISSUE THREAD

**Issue by BillH99999** [speedball2001/nompsort-mx#11]
I just got updated to TB 115 and notice that this extension is not compatible.  Are there plans to make it compatible?

Thanks,
Bill

**Comment by speedball2001** [comment]
Due to other commitments I didn't have any time yet to even research if it is still possible to support TB115. I plan to look into it but can't promise anything.

**Comment by BillH99999** [comment]
OK... that's great.  I was hoping.  

Thanks,
Bill

**Comment by speedball2001** [comment]
Could you please test version 3 and let me know if it works for you? You'll find it under [releases ](https://github.com/speedball2001/nompsort-mx/releases/tag/3.0).

**Comment by BillH99999** [comment]
Works great!  Thanks for the speedy fix.  Before this extension I was frequently sorting columns accidently.

Thanks,
Bill

**Comment by cookieguru** [comment]
Seconded, thank you @speedball2001 for the fix!

Can you share the resources you used to make the fix?  I'd love to help out the next time this extension breaks, but Mozilla's extension documentation for modern versions of Thunderbird is pretty lacking.  There's nothing in [the diff](https://github.com/speedball2001/nompsort-mx/commit/d28c9a58f33eb0b6362bc3ce441f748442c4d1d0) that makes me say "oh that's obvious"

**Comment by BillH99999** [comment]
Sorry... I spoke too soon.  It worked at first, but now even with the extension enabled, I'm able to sort columns by clicking on the header.  :(

**Comment by speedball2001** [comment]
> Sorry... I spoke too soon. It worked at first, but now even with the extension enabled, I'm able to sort columns by clicking on the header. :(

Can you reproduce how it switched from working to not working? 

Does it help to restart Thunderbird?

**Comment by speedball2001** [comment]
> Seconded, thank you @speedball2001 for the fix!
> 
> Can you share the resources you used to make the fix? I'd love to help out the next time this extension breaks, but Mozilla's extension documentation for modern versions of Thunderbird is pretty lacking. There's nothing in [the diff](https://github.com/speedball2001/nompsort-mx/commit/d28c9a58f33eb0b6362bc3ce441f748442c4d1d0) that makes me say "oh that's obvious"

Nompsort does pretty much only one thing: Find the table (in Thunderbird-speak called threadPane), attach a click listener to it and be done with it.

In TB102 and earlier the tread pane was called threadPaneBox and was implemented in XUL. In TB115 the structure changed a bit. It's now implemented using HTML `<table>` with a slightly different but easier to understand structure. And the whole thing is now embedded in a "sub browser".

Finding that browser and the table header happens in [implementation.js](https://github.com/speedball2001/nompsort-mx/blob/d28c9a58f33eb0b6362bc3ce441f748442c4d1d0/nompsapi/implementation.js#L24-L28).

As the click listener is now attached only to the header instead of the whole table it's implementation is now slightly [simpler](https://github.com/speedball2001/nompsort-mx/blob/d28c9a58f33eb0b6362bc3ce441f748442c4d1d0/nompsapi/implementation.js#L50-L54) (if only I knew how to link to lines in a diff).

Also Thunderbird's Developer Tools are very helpful because they let me inspect all of the UI.

I've been doing addon development for 15 years and it's always been lots of trial and error and trying to find my way around Thunderbird's source code.

**Comment by BillH99999** [comment]
> 
> Can you reproduce how it switched from working to not working?
> 
> Does it help to restart Thunderbird?

Weird... this morning it is working again.  I don't know what I might have done to make it stop working yesterday.  I'll play around some more and see if I can figure out what I did to make it stop working (if it happens again).  Then I'll try restarting TB to see if that helps.  I did not restart TB between yesterday and today.

Bill

**Comment by BillH99999** [comment]
So far it seems to be working fine today, but I did find another problem

With the extension enabled, the little icon on the far right of the headers which allows you to add or remove columns doesn't work.  With the extension disabled, it works fine.

Bill

**Comment by speedball2001** [comment]
> With the extension enabled, the little icon on the far right of the headers which allows you to add or remove columns doesn't work. With the extension disabled, it works fine.

Good catch. I'll look into it. In the mean time, you can ctrl-click on it.

**Comment by BillH99999** [comment]
> > With the extension enabled, the little icon on the far right of the headers which allows you to add or remove columns doesn't work. With the extension disabled, it works fine.
> 
> Good catch. I'll look into it. In the mean time, you can ctrl-click on it.

What I usually do is right click on any column heading and that also gives the same menu

**Comment by speedball2001** [comment]
> Weird... this morning it is working again. I don't know what I might have done to make it stop working yesterday. I'll play around some more and see if I can figure out what I did to make it stop working (if it happens again). Then I'll try restarting TB to see if that helps. I did not restart TB between yesterday and today.

I fixed a race condition that could cause the addon to access the threadPane and before it was completely loaded.

Please try version [3.0.1](https://github.com/speedball2001/nompsort-mx/releases/tag/3.0.1).

**Comment by BillH99999** [comment]
I installed 3.0.1.  

The button for selecting columns is now working.  Clicking on a column heading does not sort the column unless I do Ctrl-click.

All seems to be working as expected.  I'll keep playing around with it.

Thanks for the hard work!

Bill

**Comment by BillH99999** [comment]
Just wanted to let you know that I've been testing it out for another couple days and everything is still working great.

Thanks again!

Bill
