### ISSUE TITLE
Doesn't sort for Protonmail

### ISSUE THREAD

**Issue by ghost** [speedball2001/nompsort-mx#5]
Hi there. This add on works well with Gmail however it doesn't seem to work with Protonmail accounts. I have two emails received today that are correctly sorted with most recent at top, however, emails from previous days are sorted from oldest (third email) to newest.

Thanks for reviewing this issue.

**Comment by speedball2001** [comment]
Can you please check if this also happens with addons disabled? No  MPSort simply blocks mouse clicks from reaching the table header. I does not influence the sorting itself. I'm very sure that the issue is caused by something else.
