### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by joelsarv** [speedball2001/nompsort-mx#6]
Not copmpliant with Thunderbird version 78.9.0.
:-(

**Comment by speedball2001** [comment]
Version 2 works with TB 78 and newer. Please make sure to update your addons via Thunderbird's Addon Manager.

**Comment by ghjm** [comment]
Just a data point: I had Thunderbird 78.12.0 with up-to-date NMPS 2.0 and it was not working.  Thunderbird offered an update to 78.13.0 and after updating, NMPS is working again.
