### ISSUE TITLE
unknown SeaMonkey support

### ISSUE THREAD

**Issue by bish0polis** [speedball2001/nompsort-mx#7]
Version 1.4 appears to be supported under SeaMonkey, but I'm not sure how newer versions work under SeaMonkey.  Do we have a support matrix that includes SeaMonkey?

I'm sorry to have some so late to the party.  Accidentally forcing a sort of my mailbox when I simply want to click on a message has been vexing me since the days when Mozilla the org actually could build an app of the same name.

**Comment by speedball2001** [comment]
I don't actively support SeaMonkey. The old version may continue to work; newer version had to be changed to work with Thunderbird's new mail extension model. I have no idea if mail extension are supported by SeaMonkey.
